extends:
  - plugin:@typescript-eslint/recommended
  - next
  - prettier
rules:
  prefer-const: warn
  react/no-unescaped-entities: off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: '^_'
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
overrides:
  - files: 'src/pages/api/**/*.ts'
    rules:
      import/no-anonymous-default-export: off
ignorePatterns:
  - node_modules
  - '**/__mocks__/*'
